<?php 
use Magento\Framework\App\Action\Action;
if($this->getConfig('enabled')){ // start enable module?>
	<?php $_productCollection = $this->getProducts();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
	?>
	<div class="rokan-bestseller">
		
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				$showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_grid';
				$showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();
			
		?>
		<?php if($this->getConfig('title')){?>
			<div class="rokan-product-heading rokan-featured-heading"><h2><?php echo $this->getConfig('title')?></h2></div>
		<?php }?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="rokan-featured-slider">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows = $this->getConfig('row_show');
			?>	
			<ul class="owl">
				<?php $_collectionSize = $_productCollection->count() ?>
				<?php $i=0; foreach ($_productCollection as $_product): ?>
					<?php if($i %$rows == 0) echo "<li class='item featuredproductslider-item'>"; ?>

						<div class="product-item">
							<?php
							$productImage = $block->getImage($_product, $image);
							if ($pos != null) {
								$position = ' style="left:' . $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight() . 'px;"';
							}
							?>
							<div class="product-photo">
								<?php // Product Image ?>
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1');?>
									<span class="image0 image-switch">
										<?php echo $productImage->toHtml(); ?>
									</span>
									<span class="image1 image-switch">
										<?php echo $productImageThumb->toHtml(); ?>
									</span>
								</a>
								<div class="quickview-product">
									<a  data-role="quickview-button" data-id="<?php echo $_product->getId(); ?>" href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_product->getId()) ?>" title="" class="ajax diamond tooltip-hover" data-placement="top" data-original-title="<?php echo ('Quick view') ?>"><i><?php echo ('Quick view') ?></i></a>
							 	</div>
							</div>
							<div class="product-info">
								<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<h3 class="product-name">
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</h3>
								<div class="product-ratting">
									<?php echo $block->getProductDetailsHtml($_product); ?>
								</div>
								<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
								<?php /* @escapeNotVerified */ echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getPriceDisplayCustom($block->getProductPrice($_product)) ?>
								<div class="product-info-cart">
									<?php if( $_product->getShortDescription()): ?>
										<div class="product-description">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
										</div>
									<?php endif; ?>
									<div class="actions clearfix">
										<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
											<div class="pull-left action-add-cart">
												<?php if ($_product->isSaleable()): ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
														<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
															<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
															<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
															<?php echo $block->getBlockHtml('formkey')?>
															<button type="submit"
																	title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
																	class="action tocart primary">
																<i class="fa fa-shopping-cart"></i>
															</button>
														</form>
												<?php else: ?>
													<?php if ($_product->getIsSalable()): ?>
														<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
											<?php
												$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
											?>
											<div class="action-compare pull-left">
												<a href="#"
												   class="action tocompare"
												   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
											   	   role="button">
													<i class="fa fa-balance-scale"></i>
												</a>
											</div>
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
											<div class="action-wishlist pull-left">
												<a href="#"
												   class="action towishlist"
												   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
												   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
												   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
												   data-action="add-to-wishlist"
												   role="button">
													<i class="fa fa-heart-o"></i>
												</a>
											</div>
											<?php endif; ?>
										</div>
									</div>
								</div>
								
							</div>
						<?php $i++;?>
					</div>
					<?php if($i %$rows == 0) echo "</li>"; ?>                  
				<?php endforeach; ?>
					<?php if($i %$rows != 0) echo "</li>"; ?>                
			</ul>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
			<script>
				require([
					'jquery',
					'mage/mage',
					'rokanthemes/owl'
				], function ($) {
					'use strict';

					jQuery(".rokan-bestseller .owl").owlCarousel({
						lazyLoad: true,
						items : 4,
						rewind: true,
						nav : <?php echo $this->getConfig('next_back'); ?>,
						navText: [ 'prev', 'next'],
						dots: false,
						autoplayHoverPause : true,
						responsive : {
						    0 : {
						       items:1,
						    },
						    480 : {
						       items:2,
						    },
						    768 : {
						       items:3,
						    },
						    991 : {
						       items : <?php echo $this->getConfig('itemsDesktop') ? $this->getConfig('itemsDesktop') : $this->getConfig('itemsDefault'); ?>,
						    }
						}
					});
				});
			</script>
	<?php endif; ?>
	</div>
 
<?php } ?>