<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
if($banners = $block->getBannerCollection()):
	$slider = $block->getSlider();
	$sliderId = $block->getSliderId(); 
?>
<div class="wrapper_slider slider_<?php echo $sliderId; ?>">
	<div class="owl owl-carousel">
		<?php foreach($banners as $banner){	?>
			<div class="banner_item">
			<?php
			$html = $block->getImageElement($banner->getSlideImage());
			if($link = $banner->getSlideLink())
				$html = '<a href="'. $link .'">' . $html . '</a>' ; 
			echo $html;
			?>
			</div>
		<?php } ?>
	</div>
</div>
<script>
	require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';

		$(".slider_<?php echo $sliderId; ?> .owl").owlCarousel({
			items: 1,
			nav: true,
			rewind: true,
			dots: true,
			autoplay: true,
		});
	});
</script>
<?php endif; ?>
