<?php 
use Magento\Framework\App\Action\Action;
if($this->getConfig('enabled')){ // start enable module?>
	<?php $_productCollection = $this->getProducts();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
	?>
	<div class="rokan-newproduct block">
		
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid_m';
				$showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_grid_m';
				$showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();
			
		?>
		<?php if($this->getConfig('title')){?>
			<div class="rokan-product-heading rokan-onsale-heading">
				<h2><?php echo $this->getConfig('title')?></h2>
			</div>
		<?php }?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="rokan-newproduct-slider">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows = 3;
			?>	
			<div class="wrapper-new-product">
				<ul class="owl">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
						<?php if($i %$rows == 0) echo "<li class='item newproductslider-item'>"; ?>

							<div class="product-item">
							<?php
							$productImage = $block->getImage($_product, $image);
							if ($pos != null) {
								$position = ' style="left:' . $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight() . 'px;"';
							}
							?>
							<div class="product-photo pull-left">
								<?php // Product Image ?>
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1-m');?>
									<span class="image0 image-switch">
										<?php echo $productImage->toHtml(); ?>
									</span>
									<span class="image1 image-switch">
										<?php echo $productImageThumb->toHtml(); ?>
									</span>
								</a>
							</div>
							<div class="product-info">
								<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<h3 class="product-name">
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</h3>
								<div class="product-ratting">
									<?php echo $block->getProductDetailsHtml($_product); ?>
								</div>
								<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
								<?php /* @escapeNotVerified */ echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getPriceDisplayCustom($block->getProductPrice($_product)) ?>
								<?php if( $this->getConfig('description')){?>
									<div class="ma-desc">
										 <?php echo $block->getProductDetailsHtml($_product); ?>		                    
									</div>
								<?php }?>
							</div>
							<?php $i++;?>
						</div>
						<?php if($i %$rows == 0) echo "</li>"; ?>                  
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</li>"; ?>                
				</ul>
			</div>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
			<script>
				require([
					'jquery',
					'mage/mage',
					'rokanthemes/owl'
				], function ($) {
					'use strict';

					jQuery(".rokan-newproduct .owl").owlCarousel({
						lazyLoad: true,
						items : 1,
						rewind: true,
						nav : true,
						navText: [ 'prev', 'next'],
						dots: false,
					});
				});
			</script>
	<?php endif; ?>
	</div>
<?php } ?>