<?php
   /**
    * Copyright © 2015 Magento. All rights reserved.
    * See COPYING.txt for license details.
    */
   
   // @codingStandardsIgnoreFile
   
   /* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
   $_helper = $this->helper('Magento\Catalog\Helper\Output');
   ?>
<?php
   switch ($type = $block->getType()) {
   
   
   
		case 'upsell':
			/** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
			if ($exist = count($block->getItemCollection()->getItems())) {
				$type = 'upsell';
				$class = $type;

				$image = 'upsell_products_list';
				$title = __('upsell products');
				$items = $block->getItemCollection()->getItems();
				$limit = $block->getItemLimit('upsell');
				$shuffle = 0;

				$showWishlist = true;
				$showCompare = true;
				$showCart = true;
				$templateType = null;
				$description = false;
				$canItemsAddToCart = false;
			}
			break;
   
       case 'other':
       break;
   }
   ?>
<?php if ($exist):?>
<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'upsell'): ?>
<section class="block <?php echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php else: ?>
<section class="block <?php echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php endif; ?>
<?php else: ?>
<section class="block <?php echo $class; ?>">
   <?php endif; ?>
	<div class="rokan-product-heading rokan-upsell-heading">
      	<h2><?php echo $title; ?></h2>
	</div>
    
	<div class="block-content content" aria-labelledby="block-<?php echo $class?>-heading"> 
		<div id="upsell_product_slider" class="owl-carousel owl">
			<?php $iterator = 1; ?>
			<?php 
				$i = 0;
				$rows = 1;
			?>
			<?php foreach ($items as $_item): ?>
			<?php $available = ''; ?>  
			<?php
				$productImage = $block->getImage($_item, $image);
				
				
			?>
				<?php if ($i++%$rows==0) { ?>
				<div class="products-item">
				<?php } ?>
					<div class="product-item">
						<div class="product-photo">
							<a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php $productImageThumb = $block->getImage($_item, 'category_page_grid-1');?>
								<span class="image0 image-switch">
									<?php echo $productImage->toHtml(); ?>
								</span>
								<span class="image1 image-switch">
									<?php echo $productImageThumb->toHtml(); ?>
								</span>
							</a>
							<div class="quickview-product">
	                            <a href="javascript:void(0)" data-role="quickview-button" data-id="<?php echo $_item->getId(); ?>" data-href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_item->getId()) ?>" title="<?php echo $block->escapeHtml(__('Quick view')); ?>" class="ajax diamond tooltip-hover" data-placement="top" data-original-title="<?php echo ('Quick view') ?>">
	                                <i><?php echo ('Quick view') ?></i>
	                            </a>
	                        </div>
							
							<?php if ( $_item->getFinalPrice() < $_item->getPrice() ): ?>
								<span class="onsale">
									<span class="sale-bg"></span>
									<span class="sale-text"><?php echo __('Sale') ?></span>
								</span>
							<?php endif; ?>
							<?php $todayDate = time(); 
								$timeStartNew = strtotime($_item->getData('news_from_date'));
								$timeEndNew = strtotime($_item->getData('news_to_date')); ?>
							<?php if ( $timeEndNew >= $todayDate && $timeStartNew <= $todayDate): ?>
								<span class="newlabel">
									<span><?php echo __('New') ?></span>
								</span>
							<?php endif; ?>
						</div>
						<div class="product-info">
							<h3 class="product-name">
								<a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php echo $block->getProductUrl($_item) ?>">
								<?php echo $block->escapeHtml($_item->getName()) ?></a>
							</h3>
							<?php echo $block->getProductPrice($_item); ?>

							<div class="product-ratting">
								<?php if( $block->getReviewsSummaryHtml($_item, $templateType) ): ?>
									<?php echo $block->getReviewsSummaryHtml($_item, $templateType); ?>
								<?php else: ?>
									<div class="product-reviews-summary product-reviews-summary-zero" itemprop="aggregateRating" itemscope="" itemtype="http://schema.org/AggregateRating">
								        <div class="rating-summary">
									         <span class="label"><span>Rating:</span></span>
									         <div class="rating-result" title="0%">
									             <span style="width:0%"><span><span itemprop="ratingValue">0</span>% of <span itemprop="bestRating">0</span></span></span>
									         </div>
									     </div>
									</div>
								<?php endif; ?>
							</div>
							
							<div class="product-info-cart">
								<?php if( $_item->getShortDescription()): ?>
									<div class="product-description">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_item, $_item->getShortDescription(), 'short_description') ?>
									</div>
								<?php endif; ?>
								<div class="actions clearfix">
									<div class="actions-primary">
										<div class="pull-left action-add-cart">
											<?php if ($_item->isSaleable()): ?>
											<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
											<button class="btn btn-add-to-cart" data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php echo __('Add to Cart') ?>">
												<i class="fa fa-shopping-cart"></i>
											</button>
											<?php else: ?>
											<?php 
												$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
											   	$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
										   	?>
											<button class="btn btn-add-to-cart"
											   data-post='<?php echo $postData; ?>'
											   type="button" title="<?php echo __('Add to Cart') ?>">
												<i class="fa fa-shopping-cart"></i>
											</button>
											<?php endif; ?>
											<?php else: ?>
											<?php if ($_item->getIsSalable()): ?>
											<div class="stock available"><span><?php echo __('In stock') ?></span></div>
											<?php else: ?>
											<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
											<?php endif; ?>
											<?php endif; ?>
										</div>
										<?php
											$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
										?>
										<div class="action-compare pull-left">
											<a href="#"
											   class="action tocompare"
											   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>'
										   	   role="button">
												<i class="fa fa-balance-scale"></i>
											</a>
										</div>
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
										<div class="action-wishlist pull-left">
											<a href="#"
											   class="action towishlist"
											   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
											   data-action="add-to-wishlist"
											   role="button">
												<i class="fa fa-heart-o"></i>
											</a>
										</div>
										<?php endif; ?>
									</div>
								</div>
							</div>

						</div>
					</div>
					<?php if($i%$rows==0 || $i == count($items)) { ?> 
				</div> 
				<?php } ?>
			<?php endforeach ?>
		</div>
    </div> 
</section>
<?php endif;?>
<script type="text/javascript">
	require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';

		jQuery("#upsell_product_slider").owlCarousel({
			lazyLoad: true,
            items : 4,
            rewind: true,
            nav : true,
            navText: [ 'prev', 'next'],
            dots: false,
            autoplayHoverPause : true,
            responsive : {
                0 : {
                   items: 1,
                },
                479 : {
                   items: 2,
                },
                768 : {
                   items: 3,
                },
                991 : {
                   items: 4,
                }
            }
		});
	});
</script>
