<?php 
	use Magento\Framework\App\Action\Action;
	$enable = $block->getConfig('enabled');
	if($enable < 1) return ; 
	$items = $block->getConfig('items');
	$speed = $block->getConfig('speed');
	$qty = $block->getConfig('qty');
	$showCart = $block->getConfig('addtocart');
	$showWishlist = $block->getConfig('wishlist');
	$showCompare = $block->getConfig('compare');
	$show_navigation = $block->getConfig('navigation');
	$show_pagination = $block->getConfig('pagination');
	$auto = $block->getConfig('auto');
	$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
	$image = 'new_products_content_widget_grid';
	$type = 'widget-new-grid';
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
	$rows = $block->getConfig('row');
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<div class="wraper-product-tabs">
	<div class="rokan-product-heading rokan-special-heading">
		<h2><?php echo __('Our Products'); ?></h2>
		<ul class="tabs tabs-ourproducts">
			<?php 
				$tab_contents = $block->getTabContent() ; 
		    $count=0;			
			foreach($tab_contents as $tab) {
				?>
			<li rel="tab_<?php echo $tab['id'];?>" class="<?php echo $tab['class']; ?>" <?php if ($count==0) ?>> <?php echo $tab['name'];?></li>
				<?php
				$count ++; 
			}
			?>
		</ul>
	</div>
	
	<div class="tab_container"> 
	   <?php 
		foreach($tab_contents as $tab) {
		?>
		 <div id="tab_<?php echo $tab['id'];?>" class="tab_content <?php echo $tab['class']; ?>"> 
		 	<div class="productTabContent owl-carousel owl">
				<?php 
				$i=0;
				$productItems =  $tab['productInfo']; 
				foreach($productItems as $_item) { 
						$productImage = $block->getImage($_item, $image);
				?>
					<?php if($i++%$rows==0) { ?> <div class="product_row"> <?php } ?>
					<div class="product-item">
						<div class="product-content-item clearfix">
							<div class="product-photo">
								<a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
									<?php $productImageThumb = $block->getImage($_item, 'category_page_grid-1');?>
									<span class="image0 image-switch">
										<?php echo $productImage->toHtml(); ?>
									</span>
									<span class="image1 image-switch">
										<?php echo $productImageThumb->toHtml(); ?>
									</span>
								</a>
								<div class="quickview-product">
									<a  data-role="quickview-button" data-id="<?php echo $_item->getId(); ?>" href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_item->getId()) ?>" title="" class="ajax diamond tooltip-hover" data-placement="top" data-original-title="<?php echo ('Quick view') ?>"><i><?php echo ('Quick view') ?></i></a>
							 	</div>
								
								<?php if ( $_item->getFinalPrice() < $_item->getPrice() ): ?>
									<span class="onsale">
										<span class="sale-bg"></span>
										<span class="sale-text"><?php echo __('Sale') ?></span>
									</span>
								<?php endif; ?>
								<?php $todayDate = time(); 
									$timeStartNew = strtotime($_item->getData('news_from_date'));
									$timeEndNew = strtotime($_item->getData('news_to_date')); ?>
								<?php if ( $timeEndNew >= $todayDate && $timeStartNew <= $todayDate): ?>
									<span class="newlabel">
										<span><?php echo __('New') ?></span>
									</span>
								<?php endif; ?>
							</div>
							<div class="product-info">
								<h3 class="product-name">
									<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
								   href="<?php echo $block->getProductUrl($_item) ?>"
								   class="product-item-link">
										<?php echo $block->escapeHtml($_item->getName()) ?>
									</a>
								</h3>
								<?php /* @escapeNotVerified */ echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getPriceDisplayCustom($block->getProductPrice($_item)) ?>

								<div class="product-info-cart">
									<?php if( $_item->getShortDescription()): ?>
										<div class="product-description">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_item, $_item->getShortDescription(), 'short_description') ?>
										</div>
									<?php endif; ?>	
									<div class="actions clearfix">
										<div class="actions-primary">
											<?php if ( $showCart ): ?>
											<div class="pull-left action-add-cart">
												<?php if ($_item->isSaleable()): ?>
													<?php
														$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
														$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]);
														$postParams = json_decode($postData, true);
													?>
													<div class="pull-left action-add-cart">
														<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
															<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
															<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
															<?php echo $block->getBlockHtml('formkey')?>
															<button type="submit"
																	title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
																	class="btn btn-add-to-cart">
																<i class="fa fa-shopping-cart"></i>
															</button>
														</form>
													</div>
												<?php else: ?>
													<?php if ($_item->getIsSalable()): ?>
														<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
											<?php endif; ?>
											<?php
												$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
											?>
											<div class="action-compare pull-left">
												<a href="#"
												   class="action tocompare"
												   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>'
											   	   role="button">
													<i class="fa fa-balance-scale"></i>
												</a>
											</div>
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
											<div class="action-wishlist pull-left">
												<a href="#"
												   class="action towishlist"
												   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
												   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
												   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
												   data-action="add-to-wishlist"
												   role="button">
													<i class="fa fa-heart-o"></i>
												</a>
											</div>
											<?php endif; ?>
										</div>
									</div>
								</div>

							</div>
							
						</div>
					</div>
					 <?php if($i%$rows==0 || $i == count($productItems)) { ?> </div> <?php }?>
				<?php 
				}
				?>
			</div>
		 </div>
		<?php 
		} 
		?>
	</div>
</div>
<script type="text/x-magento-init">
{
	"[data-role=tocart-form], .form.map.checkout": {
		"catalogAddToCart": {}
	}
}
</script>
	
<script type="text/javascript">
require(["jquery", "rokanthemes/owl"], function($){

	$(".wraper-product-tabs .tab_content").hide();
	$(".wraper-product-tabs .tab_content:first").show();
	$(".wraper-product-tabs ul.tabs li:first").addClass("active");

	$(".wraper-product-tabs ul.tabs li").click(function() {
		$(".wraper-product-tabs ul.tabs li").removeClass("active");
		$(this).addClass("active");
		$(".wraper-product-tabs .tab_content").hide();
		$(".wraper-product-tabs .tab_content").removeClass("animate1");
		var activeTab = $(this).attr("rel"); 
		$(".wraper-product-tabs #"+activeTab) .addClass("animate1");
		$(".wraper-product-tabs #"+activeTab).fadeIn(); 
	});
	
	$(".productTabContent").owlCarousel({
		rewind : true,
		autoplay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
		nav : <?php if($show_navigation) echo 'true'; else echo 'false'; ?>,
		autoplayHoverPause : true,
		dots : <?php if($show_pagination) echo 'true'; else echo 'false'; ?>,
		responsive : {
		    0 : {
		       items: 1,
		    },
		    480 : {
		       items: 2,
		    },
		    768 : {
		       items: 3,
		    },
		    991 : {
		       items: 4,
		    }
		}
	});
	

});
 

</script> 


